// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApplication1.Data;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Modules.AuthModule.Models.Session", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("RefreshTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Revoked")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("SessionId");

                    b.HasIndex("UserId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("WebApplication1.Modules.CohortModule.Models.Cohort", b =>
                {
                    b.Property<Guid>("CohortId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("CohortId");

                    b.ToTable("Cohorts");
                });

            modelBuilder.Entity("WebApplication1.Modules.CohortModule.Models.Message", b =>
                {
                    b.Property<Guid>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CohortId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("MessageId");

                    b.HasIndex("CohortId");

                    b.HasIndex("UserId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("WebApplication1.Modules.CohortModule.Models.Notification", b =>
                {
                    b.Property<Guid>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CohortId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("NotificationId");

                    b.HasIndex("CohortId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("WebApplication1.Modules.ContestModule.Models.Contest", b =>
                {
                    b.Property<Guid>("ContestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContestDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ContestEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ContestName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("ContestStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.HasKey("ContestId");

                    b.HasIndex("ItemId");

                    b.ToTable("Contests");
                });

            modelBuilder.Entity("WebApplication1.Modules.ContestModule.Models.ContestProblem", b =>
                {
                    b.Property<Guid>("ContestId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid");

                    b.HasKey("ContestId", "ProblemId");

                    b.HasIndex("ProblemId");

                    b.ToTable("ContestProblems");
                });

            modelBuilder.Entity("WebApplication1.Modules.DuelModule.Models.Duel", b =>
                {
                    b.Property<Guid>("DuelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Cohort1Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Cohort2Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartingDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("DuelId");

                    b.HasIndex("Cohort1Id");

                    b.HasIndex("Cohort2Id");

                    b.ToTable("Duels");
                });

            modelBuilder.Entity("WebApplication1.Modules.DuelModule.Models.DuelParticipant", b =>
                {
                    b.Property<Guid>("DuelId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("DuelId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("DuelParticipants");
                });

            modelBuilder.Entity("WebApplication1.Modules.ItemModule.Models.Item", b =>
                {
                    b.Property<Guid>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<bool>("Purchasable")
                        .HasColumnType("boolean");

                    b.Property<Guid>("RarityId")
                        .HasColumnType("uuid");

                    b.HasKey("ItemId");

                    b.HasIndex("RarityId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("WebApplication1.Modules.ItemModule.Models.Purchase", b =>
                {
                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Selected")
                        .HasColumnType("boolean");

                    b.HasKey("ItemId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("WebApplication1.Modules.ItemModule.Models.Rarity", b =>
                {
                    b.Property<Guid>("RarityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("RarityName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("RarityId");

                    b.ToTable("Rarities");
                });

            modelBuilder.Entity("WebApplication1.Modules.ProblemModule.Models.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("WebApplication1.Modules.ProblemModule.Models.Difficulty", b =>
                {
                    b.Property<Guid>("DifficultyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DifficultyName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("DifficultyId");

                    b.ToTable("Difficulties");
                });

            modelBuilder.Entity("WebApplication1.Modules.ProblemModule.Models.HasTag", b =>
                {
                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.HasKey("ProblemId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("HasTags");
                });

            modelBuilder.Entity("WebApplication1.Modules.ProblemModule.Models.Language", b =>
                {
                    b.Property<Guid>("LanguageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("LanguageId");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("WebApplication1.Modules.ProblemModule.Models.PersonalizedProblem", b =>
                {
                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("ProblemId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("PersonalizedProblems");
                });

            modelBuilder.Entity("WebApplication1.Modules.ProblemModule.Models.Problem", b =>
                {
                    b.Property<Guid>("ProblemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DifficultyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DuelId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProblemTitle")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("ProblemTypeId")
                        .HasColumnType("uuid");

                    b.HasKey("ProblemId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("DifficultyId");

                    b.HasIndex("DuelId");

                    b.HasIndex("ProblemTypeId");

                    b.ToTable("Problems");
                });

            modelBuilder.Entity("WebApplication1.Modules.ProblemModule.Models.ProblemTemplate", b =>
                {
                    b.Property<Guid>("ProblemTemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid");

                    b.Property<string>("TemplateUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TestCasesUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ProblemTemplateId");

                    b.HasIndex("LanguageId");

                    b.HasIndex("ProblemId");

                    b.ToTable("ProblemTemplates");
                });

            modelBuilder.Entity("WebApplication1.Modules.ProblemModule.Models.ProblemType", b =>
                {
                    b.Property<Guid>("ProblemTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("ProblemTypeId");

                    b.ToTable("ProblemTypes");
                });

            modelBuilder.Entity("WebApplication1.Modules.ProblemModule.Models.Status", b =>
                {
                    b.Property<Guid>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("StatusId");

                    b.ToTable("Statuses");
                });

            modelBuilder.Entity("WebApplication1.Modules.ProblemModule.Models.Tag", b =>
                {
                    b.Property<Guid>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("TagId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("WebApplication1.Modules.ProblemModule.Models.UserSolution", b =>
                {
                    b.Property<Guid>("SolutionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CodeRuntimeSubmitted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid");

                    b.Property<string>("SolutionUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Stars")
                        .HasColumnType("integer");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("SolutionId");

                    b.HasIndex("LanguageId");

                    b.HasIndex("ProblemId");

                    b.HasIndex("StatusId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSolutions");
                });

            modelBuilder.Entity("WebApplication1.Modules.UserModule.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AmountSolved")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CohortId")
                        .HasColumnType("uuid");

                    b.Property<int>("Coins")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Experience")
                        .HasColumnType("integer");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfilePicture")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserRoleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("UserId");

                    b.HasIndex("CohortId");

                    b.HasIndex("UserRoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WebApplication1.Modules.UserModule.Models.UserRole", b =>
                {
                    b.Property<Guid>("UserRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("UserRoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("WebApplication1.Modules.AuthModule.Models.Session", b =>
                {
                    b.HasOne("WebApplication1.Modules.UserModule.Models.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebApplication1.Modules.CohortModule.Models.Message", b =>
                {
                    b.HasOne("WebApplication1.Modules.CohortModule.Models.Cohort", "Cohort")
                        .WithMany("Messages")
                        .HasForeignKey("CohortId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Modules.UserModule.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cohort");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebApplication1.Modules.CohortModule.Models.Notification", b =>
                {
                    b.HasOne("WebApplication1.Modules.CohortModule.Models.Cohort", "Cohort")
                        .WithMany("Notifications")
                        .HasForeignKey("CohortId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cohort");
                });

            modelBuilder.Entity("WebApplication1.Modules.ContestModule.Models.Contest", b =>
                {
                    b.HasOne("WebApplication1.Modules.ItemModule.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("WebApplication1.Modules.ContestModule.Models.ContestProblem", b =>
                {
                    b.HasOne("WebApplication1.Modules.ContestModule.Models.Contest", "Contest")
                        .WithMany("ContestProblems")
                        .HasForeignKey("ContestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Modules.ProblemModule.Models.Problem", "Problem")
                        .WithMany("ContestProblems")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contest");

                    b.Navigation("Problem");
                });

            modelBuilder.Entity("WebApplication1.Modules.DuelModule.Models.Duel", b =>
                {
                    b.HasOne("WebApplication1.Modules.CohortModule.Models.Cohort", "Cohort1")
                        .WithMany()
                        .HasForeignKey("Cohort1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Modules.CohortModule.Models.Cohort", "Cohort2")
                        .WithMany()
                        .HasForeignKey("Cohort2Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cohort1");

                    b.Navigation("Cohort2");
                });

            modelBuilder.Entity("WebApplication1.Modules.DuelModule.Models.DuelParticipant", b =>
                {
                    b.HasOne("WebApplication1.Modules.DuelModule.Models.Duel", "Duel")
                        .WithMany("DuelParticipants")
                        .HasForeignKey("DuelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Modules.UserModule.Models.User", "User")
                        .WithMany("DuelParticipants")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Duel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebApplication1.Modules.ItemModule.Models.Item", b =>
                {
                    b.HasOne("WebApplication1.Modules.ItemModule.Models.Rarity", "Rarity")
                        .WithMany()
                        .HasForeignKey("RarityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rarity");
                });

            modelBuilder.Entity("WebApplication1.Modules.ItemModule.Models.Purchase", b =>
                {
                    b.HasOne("WebApplication1.Modules.ItemModule.Models.Item", "Item")
                        .WithMany("Purchases")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Modules.UserModule.Models.User", "User")
                        .WithMany("Purchases")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebApplication1.Modules.ProblemModule.Models.HasTag", b =>
                {
                    b.HasOne("WebApplication1.Modules.ProblemModule.Models.Problem", "Problem")
                        .WithMany("HasTags")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Modules.ProblemModule.Models.Tag", "Tag")
                        .WithMany("HasTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Problem");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("WebApplication1.Modules.ProblemModule.Models.PersonalizedProblem", b =>
                {
                    b.HasOne("WebApplication1.Modules.ProblemModule.Models.Problem", "Problem")
                        .WithMany("PersonalizedProblems")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Modules.UserModule.Models.User", "User")
                        .WithMany("PersonalizedProblems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Problem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebApplication1.Modules.ProblemModule.Models.Problem", b =>
                {
                    b.HasOne("WebApplication1.Modules.ProblemModule.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Modules.ProblemModule.Models.Difficulty", "Difficulty")
                        .WithMany()
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Modules.DuelModule.Models.Duel", "Duel")
                        .WithMany()
                        .HasForeignKey("DuelId");

                    b.HasOne("WebApplication1.Modules.ProblemModule.Models.ProblemType", "ProblemType")
                        .WithMany()
                        .HasForeignKey("ProblemTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Difficulty");

                    b.Navigation("Duel");

                    b.Navigation("ProblemType");
                });

            modelBuilder.Entity("WebApplication1.Modules.ProblemModule.Models.ProblemTemplate", b =>
                {
                    b.HasOne("WebApplication1.Modules.ProblemModule.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Modules.ProblemModule.Models.Problem", "Problem")
                        .WithMany("ProblemTemplates")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Problem");
                });

            modelBuilder.Entity("WebApplication1.Modules.ProblemModule.Models.UserSolution", b =>
                {
                    b.HasOne("WebApplication1.Modules.ProblemModule.Models.Language", "Language")
                        .WithMany("UserSolutions")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Modules.ProblemModule.Models.Problem", "Problem")
                        .WithMany("UserSolutions")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Modules.ProblemModule.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Modules.UserModule.Models.User", "User")
                        .WithMany("UserSolutions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Problem");

                    b.Navigation("Status");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebApplication1.Modules.UserModule.Models.User", b =>
                {
                    b.HasOne("WebApplication1.Modules.CohortModule.Models.Cohort", "Cohort")
                        .WithMany("Users")
                        .HasForeignKey("CohortId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebApplication1.Modules.UserModule.Models.UserRole", "UserRole")
                        .WithMany()
                        .HasForeignKey("UserRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cohort");

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("WebApplication1.Modules.CohortModule.Models.Cohort", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Notifications");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("WebApplication1.Modules.ContestModule.Models.Contest", b =>
                {
                    b.Navigation("ContestProblems");
                });

            modelBuilder.Entity("WebApplication1.Modules.DuelModule.Models.Duel", b =>
                {
                    b.Navigation("DuelParticipants");
                });

            modelBuilder.Entity("WebApplication1.Modules.ItemModule.Models.Item", b =>
                {
                    b.Navigation("Purchases");
                });

            modelBuilder.Entity("WebApplication1.Modules.ProblemModule.Models.Language", b =>
                {
                    b.Navigation("UserSolutions");
                });

            modelBuilder.Entity("WebApplication1.Modules.ProblemModule.Models.Problem", b =>
                {
                    b.Navigation("ContestProblems");

                    b.Navigation("HasTags");

                    b.Navigation("PersonalizedProblems");

                    b.Navigation("ProblemTemplates");

                    b.Navigation("UserSolutions");
                });

            modelBuilder.Entity("WebApplication1.Modules.ProblemModule.Models.Tag", b =>
                {
                    b.Navigation("HasTags");
                });

            modelBuilder.Entity("WebApplication1.Modules.UserModule.Models.User", b =>
                {
                    b.Navigation("DuelParticipants");

                    b.Navigation("PersonalizedProblems");

                    b.Navigation("Purchases");

                    b.Navigation("Sessions");

                    b.Navigation("UserSolutions");
                });
#pragma warning restore 612, 618
        }
    }
}
